### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by silvareal**

### CODE REVIEW

**Comment by deven96** [comment]
Sorry I had renamed a component. Please resolve conflicts

**Comment by deven96** [comment]
Sorry Please change the feature link to this instead. I just realize the other one I gave you only stays active for 24hrs

https://PollEv.com/discourses/lkassR2jhefHuR7qeqJll/respond

**Comment by deven96** [comment]
Or instead of taking them away from the page, we can use this iframe

<iframe src="https://embed.polleverywhere.com/discourses/e3Q5zRbEngTct0DLmY9Up?controls=none&short_poll=true" width="800" height="600" frameBorder="0"></iframe>

**Comment by silvareal** [comment]
> Sorry I had renamed a component. Please resolve conflicts

fixed

**Pull request merged**
