### PR TITLE
global search

### PR DESCRIPTION
**Pull request by SLKhadeeja**

### CODE REVIEW

**Comment by silvareal** [comment]
fix conflicts

**Comment by silvareal** [comment]
just came across an issue, if you search for a particular movie and scroll to the bottom of the site, the movie engine _automatically try loading more movies_ which in turn result in an empty search data.

we will have to find better ways of displaying our search results, possibly a search page should work fine for us.

**Comment by SLKhadeeja** [comment]
Okay

**Comment by deven96** [comment]
> just came across an issue, if you search for a particular movie and scroll to the bottom of the site, the movie engine _automatically try loading more movies_ which in turn result in an empty search data.
> 
> we will have to find better ways of displaying our search results, possibly a search page should work fine for us.

 
Actually there is one engine that has paginated results... and that is the series engine
The rest only return one page.... so when making the global search @SLKhadeeja , whenever someone scrolls to the bottom of the page, it should only try to search page 2, 3, 4,e.t.c of the series engine

**Comment by SLKhadeeja** [comment]
Okay

**Pull request merged**
