### PR TITLE
Update to arrow function.

### PR DESCRIPTION
**Pull request by AdeolaFaraday**
An update was made from regular function to arrow function in the server file.

### CODE REVIEW

**Comment by silvareal** [comment]
great PR @AdeolaFaraday

**Comment by AdeolaFaraday** [comment]
Thanks.

**Comment by deven96** [comment]
You can merge the PR @silvareal

**Comment by deven96** [comment]
Cc @allcontributors add @AdeolaFaraday for code

**Review by silvareal — APPROVED** [review]

**Pull request merged**
