### PR TITLE
Relocating average stars for visibility

### PR DESCRIPTION
**Pull request by SLKhadeeja**

### CODE REVIEW

**Comment by silvareal** [comment]
Good, but the color's aren't visible and place the the rating on the image

**Comment by deven96** [comment]
Yeah place the stars on the image. I think you can leave the numbers on the card. That's what you're suggesting right @silvareal ?

**Comment by silvareal** [comment]
Ok here is what we intend achieving.
- Place the star rating on the image, take a closer look at the top of the UI and try replicating it.
Movie Card

- If you need further help on this, please don't hesitate to reach out to me.

**Comment by silvareal** [comment]
> Yeah place the stars on the image. I think you can leave the numbers on the card. That's what you're suggesting right @silvareal ?

absolutely

**Comment by SLKhadeeja** [comment]
Okay... Thanks @silvareal

**Pull request merged**
