### PR TITLE
Fix anime download

### PR DESCRIPTION
**Pull request by Mohamilr**
When the download button is clicked, it takes you to this page;

image

That happened because the url was in "http".

`Fix`
A function to replace all "http" URLs with "https"

### CODE REVIEW

**Comment by deven96** [comment]
Thanks a lot @Mohamilr

**Comment by silvareal** [comment]
@Mohamilr, thanks for your contribution

**Comment by silvareal** [comment]
@deven96 boss, you can proceed with the deploy

**Comment by deven96** [comment]
@silvareal I think the pipeline failed
https://app.travis-ci.com/github/Go-phie/gophie-web/builds/247831790

**Pull request merged**
